<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Resume - {{ $resume->first_name }} {{ $resume->last_name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12pt;
            line-height: 1.5;
            margin: 0.5in;
            color: #222;
        }
        h1 {
            font-size: 22pt;
            margin-bottom: 6pt;
            text-transform: uppercase;
            color: #1a1a1a;
        }
        h2 {
            font-size: 14.5pt;
            margin-top: 14pt;
            margin-bottom: 4pt;
            color: #004080;
            border-bottom: 1px solid #004080;
            padding-bottom: 2pt;
        }
        h3 {
            font-size: 12.5pt;
            margin: 4pt 0;
            color: #333;
        }
        p {
            margin: 2pt 0;
        }
        ul {
            margin: 3pt 0 6pt 20pt;
            padding: 0;
        }
        li {
            margin-bottom: 2pt;
        }
        .highlight {
            color: #004080;
            font-weight: bold;
        }
        .italic {
            font-style: italic;
            color: #555;
        }
        .section-header {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div style="display:flex; align-items:center; margin-bottom: 12pt;">
        @php
            $profileImagePath = $user->profile_picture 
                ? storage_path('app/public/' . $user->profile_picture) 
                : storage_path('app/public/default-avatar.jpg'); // fallback local image
        @endphp

        <div style="flex-shrink:0; margin-right:12pt;">
            <img src="{{ $profileImagePath }}" 
                alt="Profile Picture" 
                style="width:100px; height:100px; object-fit:cover; border:1px solid #ccc;">
        </div>

        <div>
            <h1 style="margin:0;">{{ $resume->first_name }} {{ $resume->last_name }}</h1>
            @if(!empty($resume->summary))
                <p class="italic" style="margin:4pt 0 0 0;">{{ $resume->summary }}</p>
            @endif
        </div>
    </div>

    <!-- Contact Info -->
    <h2>Contact</h2>
    <p><span class="highlight">Email:</span> {{ $resume->email }}</p>
    <p><span class="highlight">Phone:</span> {{ $resume->phone }}</p>
    <p><span class="highlight">Address:</span> {{ $resume->address }}, {{ $resume->city }}, {{ $resume->province }} {{ $resume->zip_code }}</p>

    <!-- Experience -->
    @if(!empty($resume->company_name))
        <h2>Experience</h2>
        <h3><span class="highlight">{{ $resume->job_title ?? '' }}</span> - <span class="italic">{{ $resume->company_name ?? '' }}</span></h3>
        <p class="italic">{{ $resume->job_start_date ? date('M Y', strtotime($resume->job_start_date)) : '' }} - {{ $resume->job_end_date ? date('M Y', strtotime($resume->job_end_date)) : 'Present' }}</p>
        @if(!empty($resume->job_description))
            <ul>
                @foreach(explode("\n", $resume->job_description) as $desc)
                    @if(trim($desc) !== '')
                        <li>{{ trim($desc) }}</li>
                    @endif
                @endforeach
            </ul>
        @endif
    @endif

    <!-- Education -->
    <h2>Education</h2>
    <h3><span class="highlight">{{ $resume->degree ?? '' }}</span> in <span class="italic">{{ $resume->field_of_study ?? '' }}</span></h3>
    <p>{{ $resume->school_name ?? '' }} — {{ $resume->grad_year }}</p>

    <!-- Certification -->
    @if(!empty($resume->certification_name))
        <h2>Certification</h2>
        <h3><span class="highlight">{{ $resume->certification_name }}</span></h3>
        <p class="italic">{{ $resume->certification_year }}</p>
    @endif

    <!-- Skills -->
    @if(!empty($resume->skills))
        <h2>Skills</h2>
        <ul>
            @foreach(explode(',', $resume->skills) as $skill)
                <li><span class="highlight">{{ trim($skill) }}</span></li>
            @endforeach
        </ul>
    @endif

    <!-- Additional Skills -->
    @if(!empty($resume->parsed_skills))
        <h2>Additional Skills</h2>
        <ul>
            @foreach(explode(',', $resume->parsed_skills) as $pskill)
                <li><span class="highlight">{{ trim($pskill) }}</span></li>
            @endforeach
        </ul>
    @endif

    <!-- Courses -->
    @if(!empty($resume->parsed_courses))
        <h2>Courses</h2>
        <ul>
            @foreach(explode(',', $resume->parsed_courses) as $course)
                <li><span class="italic">{{ trim($course) }}</span></li>
            @endforeach
        </ul>
    @endif

    <!-- Footer -->
    <p style="margin-top:20pt; font-size:10pt; color:#555;">
        Generated by MOBO Skills — {{ now()->format('Y') }}
    </p>
</body>
</html>